name: "Compile & Test"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * Mon'
jobs:

  basic:
    runs-on: ubuntu-20.04       # We need cgroup v1
    steps:
      - {uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {run: git -c protocol.file.allow=always submodule update --init}
      - {uses: cachix/install-nix-action@v12, with: {nix_path: "nixpkgs=channel:nixos-unstable"}}
      - {uses: cachix/cachix-action@v12, with: {name: thermac, signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'}}
      - name: Configure
        run: nix-shell --run "make release"
      - name: Build subprojects
        run: nix-shell --run "ninja -C build subprojects/libev/libev.a subprojects/yaml-cpp/libyaml-cpp.a subprojects/spdlog/src/libspdlog.a"
      - name: Register gcc problem matcher  # After subprojects to not see their warnings
        run: echo "::add-matcher::.github/problem-matchers/gcc.json"
      - name: Build demos-sched
        run: nix-shell --run "make"
      - name: Tests
        run: nix-shell --run "cd build && meson test --wrapper=sudo --print-errorlogs"
      - name: Build demos-sched (debug mode)
        run: nix-shell --run "make debug && make"
      - name: Tests (in debug mode)
        run: nix-shell --run "cd build && meson test --wrapper=sudo --print-errorlogs"
      - name: Generate coverage report
        run: nix-shell --run "ninja -C build coverage-xml"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./build/meson-logs
          fail_ci_if_error: true
          verbose: true
      - name: Aarch64
        run: nix-build --argstr crossSystem aarch64-linux

  other_builds:
    runs-on: ubuntu-latest
    steps:
      - {uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {run: git -c protocol.file.allow=always submodule update --init}
      - {uses: cachix/install-nix-action@v12, with: {nix_path: "nixpkgs=channel:nixos-unstable"}}
      - {uses: cachix/cachix-action@v12, with: {name: thermac, signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'}}
      - name: Register gcc problem matcher  # After subprojects to not see their warnings
        run: echo "::add-matcher::.github/problem-matchers/gcc.json"
      - name: Other builds
        run: nix-build test/test_build.nix --arg pkgsUnstable 'import <nixpkgs> {}'

  tests-unified-cgroup:
    if: false                   # Disabled until we have CGroup V2 support implemented (which may never happen)
    runs-on: ubuntu-latest
    steps:
      - {uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {run: git -c protocol.file.allow=always submodule update --init}
      - {uses: cachix/install-nix-action@v12, with: {nix_path: "nixpkgs=channel:nixos-unstable"}}
      - {uses: cachix/cachix-action@v12, with: {name: thermac, signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'}}
      - name: Build demos-sched
        run: nix-shell --run "rm -rf subprojects/*/ && make"
      - name: Run tests in VM with unified cgroup hierarchy
        working-directory: ./test
        run: |
          nix-shell -p nixos-shell ansifilter --command "nixos-shell vm-tests.nix | tee >(ansifilter > log)"
          grep 'demos-sched-tests-start\[[0-9]*\]: All tests successful.' log
