name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v6
      with:
        name: thermac
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Register gcc problem matcher
      run: echo "::add-matcher::.github/problem-matchers/gcc.json"
    - run: nix-shell --run "make"
    - run: nix-shell --run "cd build && meson test --wrapper=sudo"
    - run: nix-build test.nix
